#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Sho Yoshida　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans_sum = 0
ans_product = 1

for line in sys.stdin:
    try:
        num = float(line)
        ans_sum += num
        ans_product *= num
    except ValueError:
        print(f"数値以外のものが入力されています: {line.strip()}")

print(f"合計: {ans_sum}")
print(f"総和: {ans_product}")


